services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883" # MQTT port
      - "9001:9001" # WebSocket port (optional)
    volumes:
      - ./mosquitto/config:/mosquitto/config
    restart: unless-stopped